/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    fontSize: {
      xs: ['10px', '12px'],
      sm: ['12px', '16px'],
      md: ['14px', '18px'],
      lg: ['16px', '24px'],
      xl: ['20px', '24px'],
      '2xl': ['24px', '24px'],
      '3xl': ['34px', '32px'],
      '4xl': ['38px', '32px'],
      '5xl': ['40px', '44px'],
      '6xl': ['64px', '64px'],
      '9xl': ['96px', '149px'],
      logoSize: ['32px', '44px'],
      logoMobile: ['20px', '28px'],
      cartDesktop: ['28px', '40px'],
    },
    screens: {
      xs: '576px',
      sm: '768px',
      md: '992px',
      lg: '1200px',
      xl: '1408px',
    },
    container: {
      center: true,
      padding: '2rem',
      screens: {
        xs: '576px',
        sm: '768px',
        md: '992px',
        lg: '1200px',
        xl: '1408px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar))',
          foreground: 'hsl(var(--sidebar-foreground))',
        },
        primary: '#26777B',
        'primary-100': '#EAFAFC',
        'primary-200': '#DEF0F1',
        'primary-300': '#BDDEE0',
        'primary-400': '#99CDD0',
        'primary-500': '#7CBEC1',
        'primary-600': '#68B4B8',
        'primary-700': '#5CAFB4',
        'primary-800': '#4A999E',
        'primary-900': '#3C898D',
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      backgroundImage: {
        backGroundImg: "url('/images/home/backGroundImg.png')",
        folderLeft: "url('/images/home/folderLeft.png')",
        folderLeftIMG: "url('/images/home/folderLeftIMG.png')",
        folderRight: "url('/images/home/folderRight.png')",
        folderRightIMG: "url('/images/home/folderRightIMG.png')",
        secondBG: "url('/images/media/secondBG.png')",
        firstBG: "url('/images/media/firstBG.png')",
        womanBG: "url('/images/about/womanBG.png')",
        primaryBG: "url('/images/about/primaryBG.png')",
        cyanBG: "url('/images/about/cyanBG.png')",
        blueBG: "url('/images/about/blueBG.png')",
        mediaBG: "url('/images/media/mediaBG.png')",
        projectBG: "url('/images/projectss/projectBG.png')",
        volunteerBG: "url('/images/volunteer/volunteerBG.png')",
        donationBG: "url('/images/donation/donationBG.png')",
        specialBG: "url('/images/eventss/speacialBG.png')",
        specialBG: "url('/images/projectss/speacialBG.png')",
        partnerBG: "url('/images/partner/partnerBG.png')",
      },
      boxShadow: { '3xl': '0px 0px 20px 0px #0071BB3D' },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
